### ISSUE TITLE
Two copies of get-eligibility.js

### ISSUE THREAD

**Issue by alxhghs** [codeforboston/project-hope#9]
Is there a reason we have a copy of get-eligibility.js in /ma-health/ as well as in /js/state/massachusetts/ma-health/ ? Should we delete the copy in /ma-health/ ?

**Comment by alxhghs** [comment]
Actually, looking at my last commit it looks like I may have added the extra get-eligibility file to /ma-health/! Is that true? If so, my bad.

**Comment by filipemir** [comment]
Yes, I think so :) I think you may have pulled from a slightly outdated version of my branch. I placed it on its own branch and removed the duplicate file. We're all good now!
